name: "Build and Test Java Maven App"
description: "Checkout, setup JDK, build the project, and upload artifacts"
inputs:
  project-path:
    description: "Path to the Java project"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Build with Maven
      shell: bash
      run: mvn clean package
      working-directory: ${{ inputs.project-path }}
