name: Main Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build.yaml  # Calls the reusable workflow
    with:
      java-version: "17"
      project-path: "GHA"  # Path to the project in the repo
