name: "Reusable - Build and Test Maven Project"

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # ✅ This must be here!
        uses: actions/checkout@v3

      - name: Run Composite Action
        uses: ./.github/actions/build-maven  # ✅ Ensure correct path
        with:
          project-path: ${{ inputs.project-path }}



