name: Reusable Maven Build Workflow

on:
  workflow_call:  # Allows this workflow to be called from other workflows
    inputs:
      java-version:
        description: "Java version to use"
        required: false
        default: "17"
        type: string
      project-path:
        description: "Path to the Java Maven project"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Build with Maven
        working-directory: ${{ inputs.project-path }}  # Navigate to the project directory
        run: mvn clean package
